### ISSUE TITLE
Problem using with ESP32 on GPIO37

### ISSUE THREAD

**Issue by rowifi** [r89m/arduino-button-pushbutton#5]
Strange issue, with this GPIO37 pin. I'm using other 'input only' pins with no problem all fitted with an external pullup resistor.
All buttons are defined identically as ' PushButton' using default settings. This particular button begins it's life incorrectly as isPressed() ==True.

After the code starts, every press and release action causes the OnRelease callback to execute before the OnPress is called.
I even call update() twice before setting the callbacks to the desired function. 
The hardware is correct and all buttons are pulled high by default and go low when pressed.
GPIO37 is not normally available on the normal shielded modules, however I am using a module with an OLED that uses the chips themselves mounted on the manufacturers own PCB.
Arduino IDE set for ESP32

**Comment by r89m** [comment]
That's a shame its not working.

No idea if this is relevant, but I found this issue: https://github.com/espressif/arduino-esp32/issues/397

Also, could you make a simple sketch and check that `digitalRead` returns what you expect, eg:

```
void setup() {
    pinMode(37, INPUT);
    Serial.begin(115200);
}

void loop() {
    Serial.print("GPIO37: ");
    Serial.println(digitalRead(37));
}
```

**Comment by rowifi** [comment]
With that simple sketch, the pin reads zero (LOW ), right from startup. When the button is pressed - there is no change until it is released whereupon it reports 1 ( HIGH ) temporarily, then returns to a 0 (LOW). This is quite bizarre operation.
I would add, that this pin is also sensitive to touch and also when the neighbouring pin GPIO36 is touched, there is a distinct oscillation displayed on the GPIO37 result.
GPIO36 is currently unused  and as it happens unterminated - I would expect to see IT oscillate on touch, but not to affect GPIO37.
The pullups are 27K Ohm, which is a reasonable value. However the untouched, somewhat inverted behaviour of GPIO37 is alarmingly odd. I may need to put a storage scope on the probe to catch the pin voltages, ( or give up, assume there is a good reason why these pins are seldom available and patch the button to a different pin ). 
This does appear to be some sort of capacitor behaviour, so I examined the module, and sure enough some parts are connected to the pins. This ties up with the link you added, and also explains the coupling effect between pins.
I may investigate further but it looks like with off the shelf hardware  these pins should be used with caution. 
Not a problem with the library!


![esp32cap](https://user-images.githubusercontent.com/10230822/98345730-f65e3e80-200c-11eb-9484-7d0eda2ee57b.jpg)

**Comment by rowifi** [comment]
I have removed the capacitors, as the Espressif data sheet says to do this if these pins are to be used as GPIO. 
Then the button refused to work at all...
And now I discover I had labelled the pin numbers incorrectly so the crosstalk and inverted operation was to do with the capacitive coupling and my pcb error.
All solved now!

**Comment by r89m** [comment]
Glad to hear it's sorted, and thanks for the detailed report - hopefully if anyone else has a problem they'll find this!
